AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  stripe-lambda-python-layer

  Sample SAM Template for stripe-lambda-python-layer

Metadata:
  AWS::ServerlessRepo::Application:
    Name: stripe-lambda-python-layer
    Description: Sample Stripe Lambda Python Layer
    Author: Eduardo Janicas
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.md
    ReadmeUrl: README.md
    Labels: ['stripe', 'layer']
    HomePageUrl: https://github.com/stripe/stripe-python
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/ejanicas-stripe/stripe-lambda-python-layer

Resources:
  LambdaPythonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: stripe-lambda-python-layer
      ContentUri: source/stripe-python-layer.zip
      CompatibleRuntimes:
        - python3.11

Outputs:
  LayerArn:
    Value: !Ref LambdaPythonLayer
