AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  stripe-webhook-endpoint

  Sample SAM Template for stripe-webhook-endpoint

Metadata:
  AWS::ServerlessRepo::Application:
    Name: stripe-webhook-endpoint
    Description: Sample Stripe Webhook Listener
    Author: ejanicas@stripe.com
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.md
    ReadmeUrl: README.md
    Labels: ['tests']
    HomePageUrl: https://github.com/ejanicas-stripe/stripe-webhook-endpoint
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/ejanicas-stripe/stripe-webhook-endpoint

Parameters:
  EndpointSecretParameter:
    Type: String
    Description: Enter your webhook endpoint secret.

Resources:
  WebhookEndpointFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: webhook-endpoint/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Timeout: 5
      Environment:
        Variables:
          ENDPOINT_SECRET: 
            Ref: EndpointSecretParameter
      Events:
        WebhookEndpoint:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /webhook
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WebhookEndpointApi:
    Description: "API Gateway endpoint URL for Prod stage for Webhook Endpoint function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook/"
  WebhookEndpointFunction:
    Description: "Webhook Endpoint Lambda Function ARN"
    Value: !GetAtt WebhookEndpointFunction.Arn
  WebhookEndpointFunctionIamRole:
    Description: "Implicit IAM Role created for Webhook Endpoint function"
    Value: !GetAtt WebhookEndpointFunctionRole.Arn
